name: Git Hooks

on:
  workflow_dispatch: # Activate this workflow manually
  pull_request:

jobs:

  black:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/python_cache/

      - name: Install Haystack
        run: |
          pip install --upgrade pip
          pip install .[dev]

      - name: Black
        run: black .

      - name: Check status
        run: |
          if [[ `git status --porcelain` ]]; then
            git status
            echo ""
            echo "CHECK FAILED! Black found issues with your code formatting."
            echo ""
            echo "Either:"
            echo "1. Run Black locally before committing:
            echo ""
            echo "    pip install black==22.6.0"
            echo "    black ."
            echo ""
            echo "2. Install the pre-commit hook:"
            echo ""
            echo "    pre-commit install --hook-type pre-push"
            echo ""
            echo "3. See https://github.com/deepset-ai/haystack/blob/master/CONTRIBUTING.md for help."
            echo ""
            echo "If you have further problems, please open an issue: https://github.com/deepset-ai/haystack/issues"
            echo ""
            exit 1
          fi

  tutorials:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/python_cache/

      - name: Install Haystack
        run: |
          pip install --upgrade pip
          pip install .[dev]

      - name: Tutorial Updates
        run: python .github/utils/convert_notebooks_into_webpages.py

      - name: Check status
        run: |
          if [[ `git status --porcelain` ]]; then
            git status
            echo ""
            echo "CHECK FAILED! There are updates to be made to the tutorials."
            echo ""
            echo "Please run the tutorials documentation update script:
            echo ""
            echo "    python .github/utils/convert_notebooks_into_webpages.py"
            echo ""
            echo "or see https://github.com/deepset-ai/haystack/blob/master/CONTRIBUTING.md for help."
            echo ""
            echo "If you have further problems, please open an issue: https://github.com/deepset-ai/haystack/issues"
            echo ""
            exit 1
          fi

  openapi:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/python_cache/

      - name: Install Haystack
        run: |
          pip install --upgrade pip
          pip install .[dev]
          pip install -U rest_api/

      - name: Update OpenAPI specs
        run: python .github/utils/generate_openapi_specs.py

      - name: Check status
        run: |
          if [[ `git status --porcelain` ]]; then
            git status
            echo ""
            echo "CHECK FAILED! OpenAPI specs were not updated."
            echo ""
            echo "Please generate the new OpenAPI specs locally:
            echo ""
            echo "    python .github/utils/generate_openapi_specs.py"
            echo ""
            echo "Or see https://github.com/deepset-ai/haystack/blob/master/CONTRIBUTING.md for help."
            echo ""
            echo "If you have further problems, please open an issue: https://github.com/deepset-ai/haystack/issues"
            echo ""
            exit 1
          fi

  yaml-schemas:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/python_cache/

      - name: Install sndfile
        run: sudo apt update && sudo apt-get install libsndfile1 ffmpeg

      - name: Install Haystack
        run: |
          pip install --upgrade pip
          pip install -U .[all]

      - name: Update pipeline YAML schemas
        run: python .github/utils/generate_json_schema.py

      - name: Check status
        run: |
          if [[ `git status --porcelain` ]]; then
            git status
            echo ""
            echo "CHECK FAILED! The YAML schemas for pipelines were not updated."
            echo ""
            echo "Please generate the new schemas locally:
            echo ""
            echo "    python .github/utils/generate_json_schema.py"
            echo ""
            echo "Or see https://github.com/deepset-ai/haystack/blob/master/CONTRIBUTING.md for help."
            echo ""
            echo "If you have further problems, please open an issue: https://github.com/deepset-ai/haystack/issues"
            echo ""
            exit 1
          fi

  api-docs:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/python_cache/

      - name: Install Haystack
        run: |
          pip install --upgrade pip
          pip install -U .[dev]

      - name: Update API documentation
        run: .github/utils/pydoc-markdown.sh

      - name: Check status
        run: |
          if [[ `git status --porcelain` ]]; then
            git status
            echo ""
            echo "CHECK FAILED! The API docs were not updated."
            echo ""
            echo "Either:"
            echo "1. Generate the new API docs locally before committing:
            echo ""
            echo "    .github/utils/pydoc-markdown.sh"
            echo ""
            echo "2. Install the pre-commit hook:"
            echo ""
            echo "    pre-commit install --hook-type pre-push"
            echo ""
            echo "3. See https://github.com/deepset-ai/haystack/blob/master/CONTRIBUTING.md for help."
            echo ""
            echo "If you have further problems, please open an issue: https://github.com/deepset-ai/haystack/issues"
            echo ""
            exit 1
          fi
